# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Image-Scale2x
version:      0.02
version_from: lib/GD/Image/Scale2x.pm
installdirs:  site
requires:
    GD:                            0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
