---
abstract: 'Implementation of the Scale2x algorithm for the GD library'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: GD-Image-Scale2x
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Scale2x: 0
  GD: 0
  perl: 5.6.0
version: 0.06
